With CTE AS (
    SELECT 
    TO_TIMESTAMP(STARTED_AT) started_at,
    DATE(TO_TIMESTAMP(STARTED_AT)) DATE_STARTED_AT,
    HOUR(TO_TIMESTAMP(STARTED_AT)) HOUR_STARTED_AT,
    CASE 
    WHEN DAYNAME(TO_TIMESTAMP(STARTED_AT)) IN ('SAT','SUN')
    THEN 'WEEKEND'
    ELSE 'BUSINESSDAY'
    END AS DAY_TYPE,
    CASE 
    WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (12,1,2)
    THEN 'WINTER'
    WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (3,4,5)
    THEN 'SPRING'
    WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (6,7,8)
    THEN 'SUMMER'
    ELSE 'AUTUMN'
    END AS SEASON_TYPE
    FROM {{ source('demo', 'bike') }}
    where started_at!='started_at'
)
select * from cte